version: "3.6"

# NB:
# docker-compose automagically loads environment variables defined in an `.env` file
# router will route ports: [ 80, 53, 67 ]
# 
# TODO:
# - does pihole require the default network?

volumes:
  pihole:
  db:
  nextcloud:
  wordpress:
  syncthing-config:
  onedrive-config:
  pcloud-cache:
  # proxy
  proxy-certs:
  proxy-conf:
  proxy-dhparam:
  proxy-html:
  proxy-vhost:
  # proxy-acme
  acme-acme:

services:

  proxy:
    container_name: proxy
    image: nginxproxy/nginx-proxy:latest
    restart: always
    volumes:
      - proxy-html:/usr/share/nginx/html
      - proxy-dhparam:/etc/nginx/dhparam
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-certs:/etc/nginx/certs
      - proxy-conf:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    ports:
      - 80:80
      - 443:443

  acme:
    container_name: proxy-acme
    image: nginxproxy/acme-companion:latest
    restart: always
    depends_on:
      - proxy
    volumes_from:
      - proxy
    volumes:
      - acme-acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: proxy
      DEFAULT_EMAIL: ${EMAIL}
    networks:
      - proxy-tier

  pihole:
    container_name: pihole
    image: pihole/pihole:2024.01.0
    restart: unless-stopped
    # depends_on:
    #   - proxy-acme
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      # - "80:80/tcp"
    environment:
      - TZ=Australia/Sydney
      - WEBPASSWORD_FILE=/run/secrets/pihole_password
      - PORT=80
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=pihole.${DOMAIN}
      - LETSENCRYPT_HOST=pihole.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    # Volumes store your data between container upgrades
    volumes:
      - pihole:/etc
    secrets:
      - pihole_password
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #  - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    networks:
      - proxy-tier
      - default

  db:
    container_name: db
    image: ghcr.io/linuxserver/mariadb
    restart: always
    volumes:
      - db:/config
    # ports:
    #   - 3306:3306

  nextcloud:
    container_name: nextcloud
    image: nextcloud:27-apache
    restart: always
    expose:
      - 80
    environment:
      - PORT=80
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=nc.${DOMAIN}
      - LETSENCRYPT_HOST=nc.${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - OVERWRITEPROTOCOL=https
      - MYSQL_HOST=db
      - MYSQL_USER=nextclouduser
      - MYSQL_PASSWORD_FILE=/run/secrets/db_nextcloud_password
      - MYSQL_DATABASE=nextcloud
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - db
      # - proxy-acme
    networks:
      - proxy-tier
      - default
    secrets:
      - db_nextcloud_password

  wordpress:
    container_name: wordpress
    image: wordpress:6.4.2
    restart: always
    environment:
      - PORT=80
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpressuser
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_wordpress_password
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db
      # - proxy-acme
    networks:
      - proxy-tier
      - default
    secrets:
      - db_wordpress_password

  samba:
    container_name: samba
    image: ghcr.io/servercontainers/samba:smbd-only-latest
    restart: unless-stopped
    environment:
      # SAMBA_CONF_LOG_LEVEL: 3
      ACCOUNT_sambauser: PASSWORD
      UID_sambauser: SAMBAUSERID
      SAMBA_VOLUME_CONFIG_share: |
        [share]
         path=/shares/share
         force user = sambauser
         available = yes
         browsable = yes
         writable = yes
         read only = no
         public = no
         guest ok = no
    volumes:
      - /home/sambauser/share:/shares/share
    ports:
      - 137:137
      - 138:138
      - 139:139
      - 445:445

networks:
  proxy-tier:

secrets:
  db_nextcloud_password:
    file: secrets/db_nextcloud_password
  db_wordpress_password:
    file: secrets/db_wordpress_password
  pihole_password:
    file: secrets/pihole_password
